export const ENTERPRISE_GENERAL_FETCH_REQUEST =
  "ENTERPRISE_GENERAL_FETCH_REQUEST";
export const ENTERPRISE_GENERAL_FETCH_FAILURE =
  "ENTERPRISE_GENERAL_FETCH_FAILURE";
export const ENTERPRISE_GENERAL_FETCH_SUCCESS =
  "ENTERPRISE_GENERAL_FETCH_SUCCESS";

export const ENTERPRISE_PROJECTS_FETCH_REQUEST =
  "ENTERPRISE_PROJECTS_FETCH_REQUEST";
export const ENTERPRISE_PROJECTS_FETCH_FAILURE =
  "ENTERPRISE_PROJECTS_FETCH_FAILURE";
export const ENTERPRISE_PROJECTS_FETCH_SUCCESS =
  "ENTERPRISE_PROJECTS_FETCH_SUCCESS";

export const ENTERPRISE_USERS_FETCH_REQUEST = "ENTERPRISE_USERS_FETCH_REQUEST";
export const ENTERPRISE_USERS_FETCH_FAILURE = "ENTERPRISE_USERS_FETCH_FAILURE";
export const ENTERPRISE_USERS_FETCH_SUCCESS = "ENTERPRISE_USERS_FETCH_SUCCESS";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_PERSON_FETCH_REQUEST = "USER_FETCH_PERSONS_REQUEST";
export const USER_PERSON_FETCH_FAILURE = "USER_PERSON_FETCH_FAILURE";
export const USER_PERSON_FETCH_SUCCESS = "USER_PERSON_FETCH_SUCCESS";

export const USER_PERSON_SIGNUP_REQUEST = "USER_PERSON_SIGNUP_REQUEST";
export const USER_PERSON_SIGNUP_FAILURE = "USER_PERSON_SIGNUP_FAILURE";
export const USER_PERSON_SIGNUP_SUCCESS = "USER_PERSON_SIGNUP_SUCCESS";

export const USER_EXISTS_CHECK_REQUEST = "USER_EXISTS_CHECK_REQUEST";
export const USER_EXISTS_CHECK_FAILURE = "USER_EXISTS_CHECK_FAILURE";
export const USER_EXISTS_CHECK_SUCCESS = "USER_EXISTS_CHECK_SUCCESS";

export const PERSON_FETCH_REQUEST = "PERSON_FETCH_REQUEST";
export const PERSON_FETCH_FAILURE = "PERSON_FETCH_FAILURE";
export const PERSON_FETCH_SUCCESS = "PERSON_FETCH_SUCCESS";

export const GENERAL_PERSONS_BRIEF_FETCH_REQUEST =
  "GENERAL_PERSONS_BRIEF_FETCH_REQUEST";
export const GENERAL_PERSONS_BRIEF_FETCH_FAILURE =
  "GENERAL_PERSONS_BRIEF_FETCH_FAILURE";
export const GENERAL_PERSONS_BRIEF_FETCH_SUCCESS =
  "GENERAL_PERSONS_BRIEF_FETCH_SUCCESS";

export const GENERAL_GITLAB_SERVER_FETCH_REQUEST =
  "GENERAL_GITLAB_SERVER_FETCH_REQUEST";
export const GENERAL_GITLAB_SERVER_FETCH_FAILURE =
  "GENERAL_GITLAB_SERVER_FETCH_FAILURE";
export const GENERAL_GITLAB_SERVER_FETCH_SUCCESS =
  "GENERAL_GITLAB_SERVER_FETCH_SUCCESS";

export const GENERAL_ACHIEVEMENTS_FETCH_REQUEST =
  "GENERAL_ACHIEVEMENTS_FETCH_REQUEST";
export const GENERAL_ACHIEVEMENTS_FETCH_FAILURE =
  "GENERAL_ACHIEVEMENTS_FETCH_FAILURE";
export const GENERAL_ACHIEVEMENTS_FETCH_SUCCESS =
  "GENERAL_ACHIEVEMENTS_FETCH_SUCCESS";

export const PERSON_SETTINGS_UPDATE_REQUEST = "PERSON_SETTINGS_UPDATE_REQUEST";
export const PERSON_SETTINGS_UPDATE_FAILURE = "PERSON_SETTINGS_UPDATE_FAILURE";
export const PERSON_SETTINGS_UPDATE_SUCCESS = "PERSON_SETTINGS_UPDATE_SUCCESS";

export const PERSON_META_LINK_ADD_REQUEST = "PERSON_META_LINK_ADD_REQUEST";
export const PERSON_META_LINK_ADD_FAILURE = "PERSON_META_LINK_ADD_FAILURE";
export const PERSON_META_LINK_ADD_SUCCESS = "PERSON_META_LINK_ADD_SUCCESS";

export const PERSON_META_LINK_DELETE_REQUEST =
  "PERSON_META_LINK_DELETE_REQUEST";
export const PERSON_META_LINK_DELETE_FAILURE =
  "PERSON_META_LINK_DELETE_FAILURE";
export const PERSON_META_LINK_DELETE_SUCCESS =
  "PERSON_META_LINK_DELETE_SUCCESS";

export const PERSON_PROFILES_FETCH_REQUEST = "PERSON_PROFILES_FETCH_REQUEST";
export const PERSON_PROFILES_FETCH_FAILURE = "PERSON_PROFILES_FETCH_FAILURE";
export const PERSON_PROFILES_FETCH_SUCCESS = "PERSON_PROFILES_FETCH_SUCCESS";

export const PERSON_PROFILE_ADD_REQUEST = "PERSON_PROFILE_ADD_REQUEST";
export const PERSON_PROFILE_ADD_FAILURE = "PERSON_PROFILE_ADD_FAILURE";
export const PERSON_PROFILE_ADD_SUCCESS = "PERSON_PROFILE_ADD_SUCCESS";

export const PERSON_PROFILE_DELETE_REQUEST = "PERSON_PROFILE_DELETE_REQUEST";
export const PERSON_PROFILE_DELETE_FAILURE = "PERSON_PROFILE_DELETE_FAILURE";
export const PERSON_PROFILE_DELETE_SUCCESS = "PERSON_PROFILE_DELETE_SUCCESS";

export const PERSON_PROFILE_UPDATE_REQUEST = "PERSON_PROFILE_UPDATE_REQUEST";
export const PERSON_PROFILE_UPDATE_FAILURE = "PERSON_PROFILE_UPDATE_FAILURE";
export const PERSON_PROFILE_UPDATE_SUCCESS = "PERSON_PROFILE_UPDATE_SUCCESS";

export const PERSON_INSTAGRAM_POSTS_FETCH_REQUEST =
  "PERSON_INSTAGRAM_POSTS_FETCH_REQUEST";
export const PERSON_INSTAGRAM_POSTS_FETCH_FAILURE =
  "PERSON_INSTAGRAM_POSTS_FETCH_FAILURE";
export const PERSON_INSTAGRAM_POSTS_FETCH_SUCCESS =
  "PERSON_INSTAGRAM_POSTS_FETCH_SUCCESS";

export const PERSON_PROFILES_PROCESS_REQUEST =
  "PERSON_PROFILES_PROCESS_REQUEST";
export const PERSON_PROFILES_PROCESS_FAILURE =
  "PERSON_PROFILES_PROCESS_FAILURE";
export const PERSON_PROFILES_PROCESS_SUCCESS =
  "PERSON_PROFILES_PROCESS_SUCCESS";

export const PERSON_FOLLOW_REQUEST = "PERSON_FOLLOW_REQUEST";
export const PERSON_FOLLOW_FAILURE = "PERSON_FOLLOW_FAILURE";
export const PERSON_FOLLOW_SUCCESS = "PERSON_FOLLOW_SUCCESS";

export const PERSON_UNFOLLOW_REQUEST = "PERSON_UNFOLLOW_REQUEST";
export const PERSON_UNFOLLOW_FAILURE = "PERSON_UNFOLLOW_FAILURE";
export const PERSON_UNFOLLOW_SUCCESS = "PERSON_UNFOLLOW_SUCCESS";

export const PERSON_LIKE_REQUEST = "PERSON_LIKE_REQUEST";
export const PERSON_LIKE_FAILURE = "PERSON_LIKE_FAILURE";
export const PERSON_LIKE_SUCCESS = "PERSON_LIKE_SUCCESS";

export const PERSON_UNLIKE_REQUEST = "PERSON_UNLIKE_REQUEST";
export const PERSON_UNLIKE_FAILURE = "PERSON_UNLIKE_FAILURE";
export const PERSON_UNLIKE_SUCCESS = "PERSON_UNLIKE_SUCCESS";

export const PERSON_ACHIEVEMENT_REDEEM_REQUEST =
  "PERSON_ACHIEVEMENT_REDEEM_REQUEST";
export const PERSON_ACHIEVEMENT_REDEEM_FAILURE =
  "PERSON_ACHIEVEMENT_REDEEM_FAILURE";
export const PERSON_ACHIEVEMENT_REDEEM_SUCCESS =
  "PERSON_ACHIEVEMENT_REDEEM_SUCCESS";

export const PERSON_TALK_ADD_REQUEST = "PERSON_TALK_ADD_REQUEST";
export const PERSON_TALK_ADD_FAILURE = "PERSON_TALK_ADD_FAILURE";
export const PERSON_TALK_ADD_SUCCESS = "PERSON_TALK_ADD_SUCCESS";

export const PERSON_TALK_DELETE_REQUEST = "PERSON_TALK_DELETE_REQUEST";
export const PERSON_TALK_DELETE_FAILURE = "PERSON_TALK_DELETE_FAILURE";
export const PERSON_TALK_DELETE_SUCCESS = "PERSON_TALK_DELETE_SUCCESS";

export const TALK_FETCH_REQUEST = "TALK_FETCH_REQUEST";
export const TALK_FETCH_FAILURE = "TALK_FETCH_FAILURE";
export const TALK_FETCH_SUCCESS = "TALK_FETCH_SUCCESS";

export const TALKS_FETCH_REQUEST = "TALKS_FETCH_REQUEST";
export const TALKS_FETCH_FAILURE = "TALKS_FETCH_FAILURE";
export const TALKS_FETCH_SUCCESS = "TALKS_FETCH_SUCCESS";

export const TALK_UPDATE_REQUEST = "TALK_UPDATE_REQUEST";
export const TALK_UPDATE_FAILURE = "TALK_UPDATE_FAILURE";
export const TALK_UPDATE_SUCCESS = "TALK_UPDATE_SUCCESS";

export const TALK_COMMENT_ADD_REQUEST = "TALK_COMMENT_ADD_REQUEST";
export const TALK_COMMENT_ADD_FAILURE = "TALK_COMMENT_ADD_FAILURE";
export const TALK_COMMENT_ADD_SUCCESS = "TALK_COMMENT_ADD_SUCCESS";

export const TALK_COMMENT_DELETE_REQUEST = "TALK_COMMENT_DELETE_REQUEST";
export const TALK_COMMENT_DELETE_FAILURE = "TALK_COMMENT_DELETE_FAILURE";
export const TALK_COMMENT_DELETE_SUCCESS = "TALK_COMMENT_DELETE_SUCCESS";

export const TALK_COMMENT_UPDATE_REQUEST = "TALK_COMMENT_UPDATE_REQUEST";
export const TALK_COMMENT_UPDATE_FAILURE = "TALK_COMMENT_UPDATE_FAILURE";
export const TALK_COMMENT_UPDATE_SUCCESS = "TALK_COMMENT_UPDATE_SUCCESS";
