export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_PERSON_FETCH_REQUEST = "USER_FETCH_PERSONS_REQUEST";
export const USER_PERSON_FETCH_FAILURE = "USER_PERSON_FETCH_FAILURE";
export const USER_PERSON_FETCH_SUCCESS = "USER_PERSON_FETCH_SUCCESS";

export const PERSON_FETCH_REQUEST = "PERSON_FETCH_REQUEST";
export const PERSON_FETCH_FAILURE = "PERSON_FETCH_FAILURE";
export const PERSON_FETCH_SUCCESS = "PERSON_FETCH_SUCCESS";

export const PERSON_PERSONS_BRIEF_FETCH_REQUEST =
  "PERSON_PERSONS_BRIEF_FETCH_REQUEST";
export const PERSON_PERSONS_BRIEF_FETCH_FAILURE =
  "PERSON_PERSONS_BRIEF_FETCH_FAILURE";
export const PERSON_PERSONS_BRIEF_FETCH_SUCCESS =
  "PERSON_PERSONS_BRIEF_FETCH_SUCCESS";

export const GENERAL_GITLAB_SERVER_FETCH_REQUEST =
  "GENERAL_GITLAB_SERVER_FETCH_REQUEST";
export const GENERAL_GITLAB_SERVER_FETCH_FAILURE =
  "GENERAL_GITLAB_SERVER_FETCH_FAILURE";
export const GENERAL_GITLAB_SERVER_FETCH_SUCCESS =
  "GENERAL_GITLAB_SERVER_FETCH_SUCCESS";
